---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nicholasjackson/fake-service:v0.23.1
          ports:
            - containerPort: 9090
          env:
          - name : NAME
            value: "app"
          - name: UPSTREAM_URIS
            value: "http://db"
          - name: MESSAGE
            value: "App"
      serviceAccountName: app
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090